### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by RedRoboHood** [skylight-software/jonathan-server#7]
I'm thinking that it might be better to use a single repository for Jonathan, with subdirectories `cloud`, `server`, `client`, and `doc`. The `client` subdirectory would itself be split into different subdirectories for `windows` and any other clients we build, with maybe some code shared among different clients.

The main incentive for a single repository is keeping versioning and interdependencies straight. With separate repositories, we wouldn't be able to be sure that version 0.3.2 of the server is compatible with version 0.3.2 of the client or vice versa (i.e. the different repositories wouldn't be synchronized), but with a single repository, those sorts of compatibility issues would be obvious simply because of the repository version history.

Should we continue using separate repositories, or should we use a single repository instead?

**Comment by RedRoboHood** [comment]
I created a `jonathan` repository for example purposes. The `master` and `develop` branches would be used as specified by [Gitflow](http://nvie.com/posts/a-successful-git-branching-model/), and the `gh-pages` branch would be used for Jonathan's website. We can easily redirect the current URL of `skylight-software.github.io/jonathan` to any domain name we like once we settle on one.

**Comment by miller9904** [comment]
No, this is a bad idea.  I tried to do this with the old Jonathan repository, and it got all strung out.  Plus, why would we want to have all the different parts on the same version number?  We want to be able to update the back end without the clients even noticing.  this is something I feel we must do.

Good documentation should negate any adverse affects of not having exactly the same version numbers.  Besides, we can always issue patches if we need to change the address of web endpoints.  On that note, when we hardcode web addresses into the code, let's store them all in a separate object to allow for super easy patching.

**Comment by miller9904** [comment]
Plus, we need the ability to track bugs on each separate part of the project.

**Comment by RedRoboHood** [comment]
OK, makes sense; I deleted the example repository. We just need to make sure to keep the documentation accurate and up to date.

On that note, I'm thinking that the `jonathan-documentation` repository should have just a `master` branch (i.e. don't use Gitflow), because since it's not actually executable code, there's very little risk of breaking something by pushing an incorrect change prematurely. Also, the documentation will have information relating to past, present, and future versions of all aspects of the project, so it's not as temporally bound as the other projects.

**Comment by miller9904** [comment]
OK, sounds good.
