### ISSUE TITLE
Lightweight app for testing user interaction

### ISSUE THREAD

**Issue by miller9904** [skylight-software/jonathan-server#8]
Why don't we build a lightweight app that only has a few predictive capabilities and doesn't require a server to learn how the user will interact with cards?  You see, right now we don't have a good idea about how the user will interact with the information we give them.  This could be a tool for us to learn how to create our predictive algorithms.  What do you think?  It would be a web app, and we could always make native wrapper apps if we wanted to.

**Comment by miller9904** [comment]
It wouldn't be as private, because we would have to use cloud services such as geocoding.  But it's a good start.

**Comment by RedRoboHood** [comment]
Good idea. So, should we create a `jonathan-lightweight` repository for this that we host on GitHub Pages (i.e. rename `master` branch to `gh-pages`), then build the app there?

**Comment by miller9904** [comment]
No, I want a new name.  I was thinking of something like Pulse or Impulse.  How about we design it to be a "purely predictive assistant", meaning that it wouldn't take user input through text or speech recognition.  It would connect to all of your online accounts (Google, Microsoft, Yahoo, Amazon, etc...) and serve up info based on what it thinks you would like.  You would up vote the things you liked and down vote the things you don't, and it would learn from this data.

**Comment by RedRoboHood** [comment]
The name "Impulse" works well. I'm concerned that we won't be able to get much use (and therefore information) from such a project, though; most people use services that watch everything they do, but the predictive aspects of such services are generally viewed as creepy or otherwise undesirable. How would we gain users for such a program?

**Comment by miller9904** [comment]
Our user base lies with people who want a personal assistant type app, but are creeped out with the information that is given to someone else.  This is the solution - they only share what we explicitly ask for it and they allow it.  We will also try to maximize the use they can get out of the app without sharing any info.

I'll create a repository now.

**Comment by RedRoboHood** [comment]
OK. Let's see what we can do with Impulse.
